### ISSUE TITLE
Github sign-up server error

### ISSUE THREAD

**Issue by oliverjam** [Pageclip/node-pageclip#1]
Hey, this isn't really related to node-pageclip, but I couldn't find anywhere else. Your Github OAuth seems to be broken—I get a Heroku error page whenever I try to sign in that way.

<img width="1026" alt="screen shot 2017-10-30 at 20 30 01" src="https://user-images.githubusercontent.com/9408641/32194146-6cc3d010-bdb1-11e7-8305-d0dc3b6a7d99.png">

**Comment by benogle** [comment]
Ok, thanks, I will into look this and let you know. You can also email support@pageclip.co for any issues you have.

**Comment by benogle** [comment]
Hey @oliverjam, it looks like maybe your GitHub account didn't have an email attached that was accessible by the app, and I wasn't handling the case of no email. It has been fixed. 

It looks like you created an account via email already. You can login and go to https://pageclip.co/account to attach your github account (an email on your github account is not required when attaching the Gh account to your pageclip account). Let me know if you have any other issues! Thanks for the note.

**Comment by oliverjam** [comment]
Nice one, thanks!
